spring.application.name=school

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.datasource.driver-class-name=org.postgresql.Driver

avatars.dir.path=avatars

# spring.servlet.multipart.max-file-size=10MB макс вес файла
# spring.servlet.multipart.max-request-size=10MB макс вес запроса
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update